### ISSUE TITLE
Initial Project Config on VS

### ISSUE THREAD

**Issue by parisi18** [parisi18/Qt6#1]
Branch: [project-settings](https://github.com/parisi18/Qt6/tree/project-settings)

# Description

Configure and set Visual Code Qt project using [CMake](https://doc.qt.io/qt-6.4/cmake-manual.html) for building.

# Task

- [ ] Install Qt 6.4
    - [ ] Include system's variables
    - [ ] Configure g++ settings (Qt's mingw)
- [ ] [Configure CMake](https://doc.qt.io/qt-6.4/cmake-manual.html)
     - [ ] Set CMakeList.txt
